### ISSUE TITLE
using codeblocks in if condition?

### ISSUE THREAD

**Issue by infantilo** [ycatch/mameblock#2]
Hi,
ist there any wayto get nested logical blocks (such as an AND or OR) within the if block, as it is possible in scratch?
sorry for my bad english...here's what i mean:
a block:
```
<li class="basic-block">
  <div class="block-body">
    <span class="exp-body item1">A</span> OR <span class="exp-body item2">B</span>
  </div>
  <div class="code-body">
    <span class="exp-body item1">A</span> OR <span class="exp-body item2">B</span>
  </div>
</li>
```
and i would like to be able to drag this logic block into the IF block's condition.
if A or B {}

many thanks for any reply and help!!!

**Comment by ycatch** [comment]
Hi infantilo,
Thank you for try to use mameblock.

mameblock is not support building expressions or conditions like Scrath yet.

My temporary solution is using IF-AND block like this:
```
<li class="if-block">
	<div class="block-body">
	if(<span class="exp-body item1">(i % 3 === 0)</span> AND <span class="exp-body item2">(i % 5 === 0)</span>) {
	</div>
	<div class="code-body">
	if(<span class="exp-body item1">(i % 3 === 0)</span> && <span class="exp-body item2">(i % 5 === 0)</span>) {
	</div>
	<ol>
		<li class="comment-block">
			<div class="block-body">
				/** <span class="exp-body item1">comment</span> */
			</div>
			<div class="code-body">
				/** <span class="exp-body item1">comment</span> */
			</div>
		</li>
	</ol>
	<div class="block-body">
		}
	</div>
	<div class="code-body">
		}
	</div>
</li>
```

If some one send patch for express builder use mameblock, I will merge it.

regards
